name: Check Memory

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-latest-release
            os_type: macos
            os_name: macos-latest
            arch: x86_64
            build_type: Release
          - name: macos-latest-debug
            os_type: macos
            os_name: macos-latest
            arch: x86_64
            build_type: Debug
          - name: ubuntu-latest-release
            os_type: ubuntu
            os_name: ubuntu-latest
            build_type: Release
          - name: ubuntu-latest-debug
            os_type: ubuntu
            os_name: ubuntu-latest
            build_type: Debug
          - name: windows-latest-release
            os_type: windows
            os_name: windows-latest
            build_type: Release
          - name: windows-latest-debug
            os_type: windows
            os_name: windows-latest
            build_type: Debug
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
          - name: manylinux2014-debug
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Debug
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: Check Memory
        run: free -h

      - name: Free up some space for Debug builds
        if: matrix.platform.build_type == 'Debug'
        shell: bash
        run: |
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/share/dotnet
          rm -rf /usr/local/share/dotnet

      - name: Check Memory
        run: free -h